name: "build-test"
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - master
      - "releases/*"
    tags: 
      - "*"

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          npm install
      - run: |
          npm run all
  test: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v2
      - uses: ./
  release-checks:
    name: Release Checks
    runs-on: ubuntu-20.04
    outputs:
      should-release: ${{ steps.semver.outputs.should-release }}
    steps:
      - id: semver
        name: Semantic Version Checks
        uses: ldeluigi/action-semver-checks@v0.1
  release:
    name: GitHub Release Job
    if: ${{ needs.release-checks.outputs.should-release == 'true' }}
    needs: [release-checks, test]
    runs-on: ubuntu-20.04
    steps:
      - uses: ldeluigi/action-semver-release@v0.1
